#!/bin/bash
#
#	run.sh
#
#	This is part of Shiokaze, a research-oriented fluid solver for computer graphics.
#	Created by Ryoichi Ando <rand@nii.ac.jp> on Sep 14, 2018.
#
#	Permission is hereby granted, free of charge, to any person obtaining a copy of
#	this software and associated documentation files (the "Software"), to deal in
#	the Software without restriction, including without limitation the rights to use,
#	copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the
#	Software, and to permit persons to whom the Software is furnished to do so,
#	subject to the following conditions:
#
#	The above copyright notice and this permission notice shall be included in all copies
#	or substantial portions of the Software.
#
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
#	INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
#	PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
#	HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
#	CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
#	OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
#
for d in $(find "${DIR}/build" -type d)
do
	export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$d
done
if [ "$(uname)" == 'Darwin' ]; then
	export PATH=/Applications/Mitsuba.app/Contents/MacOS:$PATH
	export PYTHONPATH=/Applications/Mitsuba.app/python/2.7:$PYTHONPATH # Assuming that Mitsuba is install at /Applications/Mitsuba.app
	export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${DIR}/local/lib/macos
elif [ "$(expr substr $(uname -s) 1 5)" == 'Linux' ]; then
	export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${DIR}/local/lib/linux
fi
cd ${DIR} && ${DIR}/build/launcher/launcher "$@"
